-- Secuencia e tabla para Departamento (Oracle 10g compatible)

CREATE SEQUENCE SEQ_DEPARTAMENTO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_DEPARTAMENTO (
    ID                  NUMBER(19,0)    NOT NULL,
    NOMBRE              VARCHAR2(200)   NOT NULL,
    CODIGO_DANE         VARCHAR2(10)    NOT NULL,
    ACTIVO              NUMBER(1,0)     DEFAULT 1 NOT NULL,
    FECHA_CREACION      DATE            DEFAULT SYSDATE NOT NULL,
    FECHA_ACTUALIZACION DATE,
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID),
    CONSTRAINT UK_DEPT_CODIGO_DANE UNIQUE (CODIGO_DANE),
    CONSTRAINT CK_DEPT_ACTIVO CHECK (ACTIVO IN (0, 1))
);

COMMENT ON TABLE  TBL_DEPARTAMENTO              IS 'Departamentos de Colombia según codificación DANE';
COMMENT ON COLUMN TBL_DEPARTAMENTO.CODIGO_DANE  IS 'Código DANE de 2 dígitos del departamento';
COMMENT ON COLUMN TBL_DEPARTAMENTO.ACTIVO       IS '1 = activo, 0 = inactivo';
