-- Secuencia y tabla para Municipio (Oracle 10g compatible)

CREATE SEQUENCE SEQ_MUNICIPIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_MUNICIPIO (
    ID                  NUMBER(19,0)    NOT NULL,
    NOMBRE              VARCHAR2(200)   NOT NULL,
    CODIGO_DANE         VARCHAR2(10)    NOT NULL,
    ACTIVO              NUMBER(1,0)     DEFAULT 1 NOT NULL,
    FECHA_CREACION      DATE            DEFAULT SYSDATE NOT NULL,
    FECHA_ACTUALIZACION DATE,
    DEPARTAMENTO_ID     NUMBER(19,0)    NOT NULL,
    CONSTRAINT PK_MUNICIPIO PRIMARY KEY (ID),
    CONSTRAINT UK_MUNI_CODIGO_DANE UNIQUE (CODIGO_DANE),
    CONSTRAINT CK_MUNI_ACTIVO CHECK (ACTIVO IN (0, 1)),
    CONSTRAINT FK_MUNICIPIO_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO_ID)
        REFERENCES TBL_DEPARTAMENTO (ID)
);

CREATE INDEX IDX_MUNICIPIO_DEPARTAMENTO ON TBL_MUNICIPIO (DEPARTAMENTO_ID);

COMMENT ON TABLE  TBL_MUNICIPIO             IS 'Municipios de Colombia según codificación DANE';
COMMENT ON COLUMN TBL_MUNICIPIO.CODIGO_DANE IS 'Código DANE de 5 dígitos del municipio';
