-- Secuencia y tabla para Cultivo (Oracle 10g compatible)

CREATE SEQUENCE SEQ_CULTIVO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_CULTIVO (
    ID                      NUMBER(19,0)    NOT NULL,
    NOMBRE_VARIEDAD         VARCHAR2(200)   NOT NULL,
    NOMBRE_CIENTIFICO       VARCHAR2(200),
    NOMBRE_COMUN            VARCHAR2(200)   NOT NULL,
    DESCRIPCION             VARCHAR2(500),
    FECHA_INICIO            DATE,
    FECHA_ESTIMADA_COSECHA  DATE,
    ACTIVO                  NUMBER(1,0)     DEFAULT 1 NOT NULL,
    FECHA_CREACION          DATE            DEFAULT SYSDATE NOT NULL,
    FECHA_ACTUALIZACION     DATE,
    PREDIO_ID               NUMBER(19,0)    NOT NULL,
    CONSTRAINT PK_CULTIVO       PRIMARY KEY (ID),
    CONSTRAINT CK_CULTIVO_ACTIVO CHECK (ACTIVO IN (0, 1)),
    CONSTRAINT FK_CULTIVO_PREDIO FOREIGN KEY (PREDIO_ID) REFERENCES TBL_PREDIO (ID)
);

CREATE INDEX IDX_CULTIVO_PREDIO ON TBL_CULTIVO (PREDIO_ID);
CREATE INDEX IDX_CULTIVO_FECHAS ON TBL_CULTIVO (FECHA_INICIO, FECHA_ESTIMADA_COSECHA);

COMMENT ON TABLE TBL_CULTIVO IS 'Cultivos registrados en los predios';

-- Tabla de relación Cultivo-Plaga (many-to-many)
-- TBL_PLAGA ya existe (creada en V4)
CREATE TABLE TBL_CULTIVO_PLAGA (
    CULTIVO_ID  NUMBER(19,0) NOT NULL,
    PLAGA_ID    NUMBER(19,0) NOT NULL,
    CONSTRAINT PK_CULTIVO_PLAGA PRIMARY KEY (CULTIVO_ID, PLAGA_ID),
    CONSTRAINT FK_CP_CULTIVO    FOREIGN KEY (CULTIVO_ID) REFERENCES TBL_CULTIVO (ID),
    CONSTRAINT FK_CP_PLAGA      FOREIGN KEY (PLAGA_ID)   REFERENCES TBL_PLAGA (ID)
);
